### ISSUE TITLE
section count is not incremented for thalamus morphologies in replace_axon

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/EModelRunner#34]
Just noticed that this `count `stays at `0` in the `for` loop, while it is incremented in the `for` loop of the SSCX `replace_axon` function. Is that normal?

_Originally posted by @AurelienJaquier in https://github.com/BlueBrain/EModelRunner/pull/31#discussion_r788782922_

**Comment by anilbey** [comment]
@elisabettai

**Comment by elisabettai** [comment]
Mmh, that sounds like a bug. Let's fix it here, knowing that we might get different results.

**Comment by anilbey** [comment]
Ok it's fixed in 0bd5d62
