### ISSUE TITLE
bluepyopt 0.13.161 changes the hoc template

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/EModelRunner#82]
### Description

The arbor changes touch the hoc template.

It effects this line in EModelRunner's hoc creation: https://github.com/BlueBrain/EModelRunner/blob/main/emodelrunner/create_hoc_tools.py#L570

Here are the differences between bluepyopt 0.13.107 vs 0.13.161 on the following test run: `tests/sscx_tests/test_emodelrunner.py::test_synapses_hoc_vs_py_script`.
https://www.diffchecker.com/oOEF0tGM/.

`channels` argument has one more item. Was it intended?
#### channels arguments before

```python
OrderedDict([('all', ['pas']), ('apical', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'NaTg', 'SKv3_1', 'Ih']), ('axonal', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'SKv3_1', 'SK_E2', 'K_Pst', 'K_Tst', 'NaTg', 'Nap_Et2']), ('basal', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'Ih']), ('somatic', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'SKv3_1', 'SK_E2', 'K_Pst', 'K_Tst', 'NaTg', 'Ih']), ('myelinated', [])])
```

#### channels arguments after

```python
(OrderedDict([('all', ['pas']), ('apical', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'NaTg', 'SKv3_1', 'Ih']), ('axonal', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'SKv3_1', 'SK_E2', 'K_Pst', 'K_Tst', 'NaTg', 'Nap_Et2']), ('basal', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'Ih']), ('somatic', ['CaDynamics_DC0', 'Ca_HVA2', 'Ca_LVAst', 'SKv3_1', 'SK_E2', 'K_Pst', 'K_Tst', 'NaTg', 'Ih']), ('myelinated', [])]), OrderedDict([('all', []), ('apical', []), ('axonal', []), ('basal', []), ('somatic', []), ('myelinated', [])]))
```

`range_parameters` argument is completely different.

#### range_parameters before

```python
[Range(location='apical', param_name='gIhbar_Ih', value='(-0.8696 + 2.087*exp((%.17g)*0.0031))*0.00016020154747782431'), Range(location='apical', param_name='gNaTgbar_NaTg', value='exp(%.17g*-0.0055559422855153305)*0.032494878816301496'), Range(location='basal', param_name='gIhbar_Ih', value='(-0.8696 + 2.087*exp((%.17g)*0.0031))*0.00016020154747782431'), Range(location='somatic', param_name='gIhbar_Ih', value='(-0.8696 + 2.087*exp((%.17g)*0.0031))*0.00016020154747782431')]
```

#### range_parameters after

```python
[RangeExpr(location='apical', name='gIhbar_Ih', value=0.0001602015474778243, value_scaler=<bluepyopt.ephys.parameterscalers.parameterscalers.NrnSegmentSomaDistanceScaler object at 0x7fba1696ad40>), RangeExpr(location='apical', name='gNaTgbar_NaTg', value=0.032494878816301496, value_scaler=<bluepyopt.ephys.parameterscalers.parameterscalers.NrnSegmentSomaDistanceScaler object at 0x7fba1696ada0>), RangeExpr(location='basal', name='gIhbar_Ih', value=0.0001602015474778243, value_scaler=<bluepyopt.ephys.parameterscalers.parameterscalers.NrnSegmentSomaDistanceScaler object at 0x7fba1696ad40>), RangeExpr(location='somatic', name='gIhbar_Ih', value=0.0001602015474778243, value_scaler=<bluepyopt.ephys.parameterscalers.parameterscalers.NrnSegmentSomaDistanceScaler object at 0x7fba1696ad40>)]
```

### Result

As a result we get this jinja exception

```shell
FAILED tests/sscx_tests/test_emodelrunner.py::test_synapses_hoc_vs_py_script 
- jinja2.exceptions.UndefinedError: 'tuple object' has no attribute 'items'
```

**Comment by anilbey** [comment]
#83 reproduces the issue on its tox run: `tox -e py3-sscx`.

```shell
  >       if hasattr(obj, "jinja_pass_arg"):
  E       jinja2.exceptions.UndefinedError: 'tuple object' has no attribute 'items'
```

Full log: https://github.com/BlueBrain/EModelRunner/actions/runs/3968756433/jobs/6802349302

**Comment by AurelienJaquier** [comment]
Given the error, I believe it is this line channels.items in the cell_template (for this case, here: https://github.com/BlueBrain/EModelRunner/blob/main/examples/sscx_sample_dir/templates/cell_template_neurodamus.jinja2#L209) that is the cause.
It looks like channels have been turned from a dict to a tuple of dicts as you explained in the description, and our cell packages do not expect that.

**Comment by AurelienJaquier** [comment]
Yes, now _generate_channels_by_location in BPO (https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/create_hoc.py#L52) returns the channels dict AND a new dict. This has been changed in the arbor PR.
So we should change this line in emodelrunner:
https://github.com/BlueBrain/EModelRunner/blob/main/emodelrunner/create_hoc_tools.py#L555
to
`channels, _ = _generate_channels_by_location(mechs, location_order)`

**Comment by anilbey** [comment]
Fantastic, thanks @AurelienJaquier .

**Comment by anilbey** [comment]
Let me test it on #83.

**Comment by anilbey** [comment]
With that change, the channels now contain the same information as before.

There's now this error again at the same line that is calling `template.render`.

```python
>   ???
E   ValueError: too many values to unpack (expected 3)

```

traceback

```python
/home/anil/git-repos/EModelRunner/emodelrunner/create_hoc.py:145: in get_hoc
    cell_hoc = cell.create_custom_hoc(
/home/anil/git-repos/EModelRunner/emodelrunner/cell.py:166: in create_custom_hoc
    ret = create_hoc(
/home/anil/git-repos/EModelRunner/emodelrunner/create_hoc_tools.py:570: in create_hoc
    return template.render(

```

**Comment by anilbey** [comment]
This line is the issue probably

https://github.com/BlueBrain/EModelRunner/blob/main/examples/sscx_sample_dir/templates/cell_template_neurodamus.jinja2#L226

**Comment by anilbey** [comment]
Because the RangeExpr has 4 parameters whereas Range has only 3

`RangeExpr = namedtuple('RangeExpr', 'location, name, value, value_scaler')`

`Range = namedtuple('Range', 'location, param_name, value')`

**Comment by anilbey** [comment]
Updating the template as below fixes that issue but now the results of a test is different.

```diff
@@ -223,8 +223,8 @@ proc biophys() {
   {%- endfor %}
   }
   {% endfor %}
-  {%- for location, param_name, value in range_params %}
-  distribute_distance(CellRef.{{location}}, "{{param_name}}", "{{value}}")
+  {%- for location, name, value, _ in range_params %}
+  distribute_distance(CellRef.{{location}}, "{{name}}", "{{value}}")
   {%- endfor %}
 }

```

```shell
FAILED tests/sscx_tests/test_emodelrunner.py::test_synapses_hoc_vs_py_script - assert 15.521013275286599 < 1e-05

```

**Comment by AurelienJaquier** [comment]
Then we have the same problem in bluepyopt, since it also unpacks range_params with 3 variables: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/templates/cell_template.jinja2#L154

**Comment by anilbey** [comment]
Ah wait, there is this function to convert a RangeExpr to a Range (the hoc one) `https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/create_hoc.py#L88`

**Comment by anilbey** [comment]
The return value of the `create_hoc` function, namely `_generate_parameters` is containing `RangeExpr` instead of `Range`.
The hoc template however is expecting a `Range`.

 https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/create_hoc.py#L183

Let's decide what to do about it the next week :)

**Comment by AurelienJaquier** [comment]
Just turn the rangeexpr into range with the function you mentioned above?

**Comment by anilbey** [comment]
But if the hoc template requires `Range`s instead of `RangeExpr`s, is there a need to create the `RangeExpr`s at all? We can directly create `Range`s in the first place inside `_generate_parameters`.

**Comment by AurelienJaquier** [comment]
I don't think we can: it is also used in create_acc.py: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/create_acc.py#L689
if we change it, it will break that module. It is probably the reason range expressions were changed in the arbor PR. I think using _range_expre_to_hoc as you suggested before if better. It is also how the bluepyopt create_hoc function uses it now: https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/create_hoc.py#L320

**Comment by anilbey** [comment]
Thanks,  the tests pass now.
